name: automerge

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci --force
        working-directory: ./ClientApp
      - run: npm run build
        working-directory: ./ClientApp
